name: Qodana
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.MD'
  push:
    paths-ignore:
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README.MD'

jobs:
  qodana:
    name: 'Qodana Job'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
          args: --baseline qodana.sarif.json
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
